In [1]:
import pandas as pd

In [2]:
dataset = pd.read_csv("auta.csv", delimiter=',')

In [3]:
dataset

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
1,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
2,1,?,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.4,10.0,102,5500,24,30,13950
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.4,8.0,115,5500,18,22,17450
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,23,28,16845
201,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,8.7,160,5300,19,25,19045
202,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,173,mpfi,3.58,2.87,8.8,134,5500,18,23,21485
203,-1,95,volvo,diesel,turbo,four,sedan,rwd,front,109.1,...,145,idi,3.01,3.4,23.0,106,4800,26,27,22470
204,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,19,25,22625

In [4]:
# ceny over 20 000
df = dataset.copy()
for idx in df.index:
    if df.loc[idx, 'price'] != '?':
        if int(df.loc[idx, 'price']) > 20000:
            print(df.loc[idx])

symboling                1
normalized-losses      158
make                  audi
fuel-type              gas
aspiration           turbo
num-of-doors          four
body-style           sedan
drive-wheels           fwd
engine-location      front
wheel-base           105.8
length               192.7
width                 71.4
height                55.9
curb-weight           3086
engine-type            ohc
num-of-cylinders      five
engine-size            131
fuel-system           mpfi
bore                  3.13
stroke                 3.4
compression-ratio      8.3
horsepower             140
peak-rpm              5500
city-mpg                17
highway-mpg             20
price                23875
Name: 8, dtype: object
symboling                0
normalized-losses      188
make                   bmw
fuel-type              gas
aspiration             std
num-of-doors           two
body-style           sedan
drive-wheels           rwd
engine-location      front
wheel-base           101.2
length               176.8
width                 64.8
height                54.3
curb-weight           2710
engine-type            ohc
num-of-cylinders       six
engine-size            164
fuel-system           mpfi
bore                  3.31
stroke                3.19
compression-ratio      9.0
horsepower             121
peak-rpm              4250
city-mpg                21
highway-mpg             28
price                20970
Name: 12, dtype: object
symboling                0
normalized-losses      188
make                   bmw
fuel-type              gas
aspiration             std
num-of-doors          four
body-style           sedan
drive-wheels           rwd
engine-location      front
wheel-base           101.2
length               176.8
width                 64.8
height                54.3
curb-weight           2765
engine-type            ohc
num-of-cylinders       six
engine-size            164
fuel-system           mpfi
bore                  3.31
stroke                3.19
compression-ratio      9.0
horsepower             121
peak-rpm              4250
city-mpg                21
highway-mpg             28
price                21105
Name: 13, dtype: object
symboling                1
normalized-losses        ?
make                   bmw
fuel-type              gas
aspiration             std
num-of-doors          four
body-style           sedan
drive-wheels           rwd
engine-location      front
wheel-base           103.5
length               189.0
width                 66.9
height                55.7
curb-weight           3055
engine-type            ohc
num-of-cylinders       six
engine-size            164
fuel-system           mpfi
bore                  3.31
stroke                3.19
compression-ratio      9.0
horsepower             121
peak-rpm              4250
city-mpg                20
highway-mpg             25
price                24565
Name: 14, dtype: object
symboling                0
normalized-losses        ?
make                   bmw
fuel-type              gas
aspiration             std
num-of-doors          four
body-style           sedan
drive-wheels           rwd
engine-location      front
wheel-base           103.5
length               189.0
width                 66.9
height                55.7
curb-weight           3230
engine-type            ohc
num-of-cylinders       six
engine-size            209
fuel-system           mpfi
bore                  3.62
stroke                3.39
compression-ratio      8.0
horsepower             182
peak-rpm              5400
city-mpg                16
highway-mpg             22
price                30760
Name: 15, dtype: object
symboling                0
normalized-losses        ?
make                   bmw
fuel-type              gas
aspiration             std
num-of-doors           two
body-style           sedan
drive-wheels           rwd
engine-location      front
wheel-base           103.5
length               193.8
width                 67.9
height                53.7
curb-weight           3380
engine-type            ohc
num-of-cylinders       six
engine-size            209
fuel-system           mpfi
bore                  3.62
stroke                3.39
compression-ratio      8.0
horsepower             182
peak-rpm              5400
city-mpg                16
highway-mpg             22
price                41315
Name: 16, dtype: object
symboling                0
normalized-losses        ?
make                   bmw
fuel-type              gas
aspiration             std
num-of-doors          four
body-style           sedan
drive-wheels           rwd
engine-location      front
wheel-base           110.0
length               197.0
width                 70.9
height                56.3
curb-weight           3505
engine-type            ohc
num-of-cylinders       six
engine-size            209
fuel-system           mpfi
bore                  3.62
stroke                3.39
compression-ratio      8.0
horsepower             182
peak-rpm              5400
city-mpg                15
highway-mpg             20
price                36880
Name: 17, dtype: object
symboling                 0
normalized-losses       145
make                 jaguar
fuel-type               gas
aspiration              std
num-of-doors           four
body-style            sedan
drive-wheels            rwd
engine-location       front
wheel-base            113.0
length                199.6
width                  69.6
height                 52.8
curb-weight            4066
engine-type            dohc
num-of-cylinders        six
engine-size             258
fuel-system            mpfi
bore                   3.63
stroke                 4.17
compression-ratio       8.1
horsepower              176
peak-rpm               4750
city-mpg                 15
highway-mpg              19
price                 32250
Name: 47, dtype: object
symboling                 0
normalized-losses         ?
make                 jaguar
fuel-type               gas
aspiration              std
num-of-doors           four
body-style            sedan
drive-wheels            rwd
engine-location       front
wheel-base            113.0
length                199.6
width                  69.6
height                 52.8
curb-weight            4066
engine-type            dohc
num-of-cylinders        six
engine-size             258
fuel-system            mpfi
bore                   3.63
stroke                 4.17
compression-ratio       8.1
horsepower              176
peak-rpm               4750
city-mpg                 15
highway-mpg              19
price                 35550
Name: 48, dtype: object
symboling                 0
normalized-losses         ?
make                 jaguar
fuel-type               gas
aspiration              std
num-of-doors            two
body-style            sedan
drive-wheels            rwd
engine-location       front
wheel-base            102.0
length                191.7
width                  70.6
height                 47.8
curb-weight            3950
engine-type            ohcv
num-of-cylinders     twelve
engine-size             326
fuel-system            mpfi
bore                   3.54
stroke                 2.76
compression-ratio      11.5
horsepower              262
peak-rpm               5000
city-mpg                 13
highway-mpg              17
price                 36000
Name: 49, dtype: object
symboling                       -1
normalized-losses               93
make                 mercedes-benz
fuel-type                   diesel
aspiration                   turbo
num-of-doors                  four
body-style                   sedan
drive-wheels                   rwd
engine-location              front
wheel-base                   110.0
length                       190.9
width                         70.3
height                        56.5
curb-weight                   3515
engine-type                    ohc
num-of-cylinders              five
engine-size                    183
fuel-system                    idi
bore                          3.58
stroke                        3.64
compression-ratio             21.5
horsepower                     123
peak-rpm                      4350
city-mpg                        22
highway-mpg                     25
price                        25552
Name: 67, dtype: object
symboling                       -1
normalized-losses               93
make                 mercedes-benz
fuel-type                   diesel
aspiration                   turbo
num-of-doors                  four
body-style                   wagon
drive-wheels                   rwd
engine-location              front
wheel-base                   110.0
length                       190.9
width                         70.3
height                        58.7
curb-weight                   3750
engine-type                    ohc
num-of-cylinders              five
engine-size                    183
fuel-system                    idi
bore                          3.58
stroke                        3.64
compression-ratio             21.5
horsepower                     123
peak-rpm                      4350
city-mpg                        22
highway-mpg                     25
price                        28248
Name: 68, dtype: object
symboling                        0
normalized-losses               93
make                 mercedes-benz
fuel-type                   diesel
aspiration                   turbo
num-of-doors                   two
body-style                 hardtop
drive-wheels                   rwd
engine-location              front
wheel-base                   106.7
length                       187.5
width                         70.3
height                        54.9
curb-weight                   3495
engine-type                    ohc
num-of-cylinders              five
engine-size                    183
fuel-system                    idi
bore                          3.58
stroke                        3.64
compression-ratio             21.5
horsepower                     123
peak-rpm                      4350
city-mpg                        22
highway-mpg                     25
price                        28176
Name: 69, dtype: object
symboling                       -1
normalized-losses               93
make                 mercedes-benz
fuel-type                   diesel
aspiration                   turbo
num-of-doors                  four
body-style                   sedan
drive-wheels                   rwd
engine-location              front
wheel-base                   115.6
length                       202.6
width                         71.7
height                        56.3
curb-weight                   3770
engine-type                    ohc
num-of-cylinders              five
engine-size                    183
fuel-system                    idi
bore                          3.58
stroke                        3.64
compression-ratio             21.5
horsepower                     123
peak-rpm                      4350
city-mpg                        22
highway-mpg                     25
price                        31600
Name: 70, dtype: object
symboling                       -1
normalized-losses                ?
make                 mercedes-benz
fuel-type                      gas
aspiration                     std
num-of-doors                  four
body-style                   sedan
drive-wheels                   rwd
engine-location              front
wheel-base                   115.6
length                       202.6
width                         71.7
height                        56.5
curb-weight                   3740
engine-type                   ohcv
num-of-cylinders             eight
engine-size                    234
fuel-system                   mpfi
bore                          3.46
stroke                         3.1
compression-ratio              8.3
horsepower                     155
peak-rpm                      4750
city-mpg                        16
highway-mpg                     18
price                        34184
Name: 71, dtype: object
symboling                        3
normalized-losses              142
make                 mercedes-benz
fuel-type                      gas
aspiration                     std
num-of-doors                   two
body-style             convertible
drive-wheels                   rwd
engine-location              front
wheel-base                    96.6
length                       180.3
width                         70.5
height                        50.8
curb-weight                   3685
engine-type                   ohcv
num-of-cylinders             eight
engine-size                    234
fuel-system                   mpfi
bore                          3.46
stroke                         3.1
compression-ratio              8.3
horsepower                     155
peak-rpm                      4750
city-mpg                        16
highway-mpg                     18
price                        35056
Name: 72, dtype: object
symboling                        0
normalized-losses                ?
make                 mercedes-benz
fuel-type                      gas
aspiration                     std
num-of-doors                  four
body-style                   sedan
drive-wheels                   rwd
engine-location              front
wheel-base                   120.9
length                       208.1
width                         71.7
height                        56.7
curb-weight                   3900
engine-type                   ohcv
num-of-cylinders             eight
engine-size                    308
fuel-system                   mpfi
bore                           3.8
stroke                        3.35
compression-ratio              8.0
horsepower                     184
peak-rpm                      4500
city-mpg                        14
highway-mpg                     16
price                        40960
Name: 73, dtype: object
symboling                        1
normalized-losses                ?
make                 mercedes-benz
fuel-type                      gas
aspiration                     std
num-of-doors                   two
body-style                 hardtop
drive-wheels                   rwd
engine-location              front
wheel-base                   112.0
length                       199.2
width                         72.0
height                        55.4
curb-weight                   3715
engine-type                   ohcv
num-of-cylinders             eight
engine-size                    304
fuel-system                   mpfi
bore                           3.8
stroke                        3.35
compression-ratio              8.0
horsepower                     184
peak-rpm                      4500
city-mpg                        14
highway-mpg                     16
price                        45400
Name: 74, dtype: object
symboling                    3
normalized-losses          186
make                   porsche
fuel-type                  gas
aspiration                 std
num-of-doors               two
body-style           hatchback
drive-wheels               rwd
engine-location          front
wheel-base                94.5
length                   168.9
width                     68.3
height                    50.2
curb-weight               2778
engine-type                ohc
num-of-cylinders          four
engine-size                151
fuel-system               mpfi
bore                      3.94
stroke                    3.11
compression-ratio          9.5
horsepower                 143
peak-rpm                  5500
city-mpg                    19
highway-mpg                 27
price                    22018
Name: 125, dtype: object
symboling                  3
normalized-losses          ?
make                 porsche
fuel-type                gas
aspiration               std
num-of-doors             two
body-style           hardtop
drive-wheels             rwd
engine-location         rear
wheel-base              89.5
length                 168.9
width                   65.0
height                  51.6
curb-weight             2756
engine-type             ohcf
num-of-cylinders         six
engine-size              194
fuel-system             mpfi
bore                    3.74
stroke                   2.9
compression-ratio        9.5
horsepower               207
peak-rpm                5900
city-mpg                  17
highway-mpg               25
price                  32528
Name: 126, dtype: object
symboling                  3
normalized-losses          ?
make                 porsche
fuel-type                gas
aspiration               std
num-of-doors             two
body-style           hardtop
drive-wheels             rwd
engine-location         rear
wheel-base              89.5
length                 168.9
width                   65.0
height                  51.6
curb-weight             2756
engine-type             ohcf
num-of-cylinders         six
engine-size              194
fuel-system             mpfi
bore                    3.74
stroke                   2.9
compression-ratio        9.5
horsepower               207
peak-rpm                5900
city-mpg                  17
highway-mpg               25
price                  34028
Name: 127, dtype: object
symboling                      3
normalized-losses              ?
make                     porsche
fuel-type                    gas
aspiration                   std
num-of-doors                 two
body-style           convertible
drive-wheels                 rwd
engine-location             rear
wheel-base                  89.5
length                     168.9
width                       65.0
height                      51.6
curb-weight                 2800
engine-type                 ohcf
num-of-cylinders             six
engine-size                  194
fuel-system                 mpfi
bore                        3.74
stroke                       2.9
compression-ratio            9.5
horsepower                   207
peak-rpm                    5900
city-mpg                      17
highway-mpg                   25
price                      37028
Name: 128, dtype: object
symboling               -1
normalized-losses       95
make                 volvo
fuel-type              gas
aspiration             std
num-of-doors          four
body-style           sedan
drive-wheels           rwd
engine-location      front
wheel-base           109.1
length               188.8
width                 68.9
height                55.5
curb-weight           3012
engine-type           ohcv
num-of-cylinders       six
engine-size            173
fuel-system           mpfi
bore                  3.58
stroke                2.87
compression-ratio      8.8
horsepower             134
peak-rpm              5500
city-mpg                18
highway-mpg             23
price                21485
Name: 202, dtype: object
symboling                -1
normalized-losses        95
make                  volvo
fuel-type            diesel
aspiration            turbo
num-of-doors           four
body-style            sedan
drive-wheels            rwd
engine-location       front
wheel-base            109.1
length                188.8
width                  68.9
height                 55.5
curb-weight            3217
engine-type             ohc
num-of-cylinders        six
engine-size             145
fuel-system             idi
bore                   3.01
stroke                  3.4
compression-ratio      23.0
horsepower              106
peak-rpm               4800
city-mpg                 26
highway-mpg              27
price                 22470
Name: 203, dtype: object
symboling               -1
normalized-losses       95
make                 volvo
fuel-type              gas
aspiration           turbo
num-of-doors          four
body-style           sedan
drive-wheels           rwd
engine-location      front
wheel-base           109.1
length               188.8
width                 68.9
height                55.5
curb-weight           3062
engine-type            ohc
num-of-cylinders      four

In [5]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 26 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   symboling          205 non-null    int64
 1   normalized-losses  205 non-null    object
 2   make               205 non-null    object
 3   fuel-type          205 non-null    object
 4   aspiration         205 non-null    object
 5   num-of-doors       205 non-null    object
 6   body-style         205 non-null    object
 7   drive-wheels       205 non-null    object
 8   engine-location    205 non-null    object
 9   wheel-base         205 non-null    float64
 10  length             205 non-null    float64
 11  width              205 non-null    float64
 12  height             205 non-null    float64
 13  curb-weight        205 non-null    int64
 14  engine-type        205 non-null    object
 15  num-of-cylinders   205 non-null    object
 16  engine-size        205 non-null    int64
 17  fuel-system        205 non-null    object
 18  bore               205 non-null    object
 19  stroke             205 non-null    object
 20  compression-ratio  205 non-null    float64
 21  horsepower         205 non-null    object
 22  peak-rpm           205 non-null    object
 23  city-mpg           205 non-null    int64
 24  highway-mpg        205 non-null    int64
 25  price              205 non-null    object
dtypes: float64(5), int64(5), object(16)
memory usage: 41.8+ KB

In [6]:
# z ignorowaniem bledow
for idx in df.index:
    try:
        if int(df.loc[idx, 'price']) > 20000:
            print(df.loc[idx])
        
    except:
        pass

symboling                1
normalized-losses      158
make                  audi
fuel-type              gas
aspiration           turbo
num-of-doors          four
body-style           sedan
drive-wheels           fwd
engine-location      front
wheel-base           105.8
length               192.7
width                 71.4
height                55.9
curb-weight           3086
engine-type            ohc
num-of-cylinders      five
engine-size            131
fuel-system           mpfi
bore                  3.13
stroke                 3.4
compression-ratio      8.3
horsepower             140
peak-rpm              5500
city-mpg                17
highway-mpg             20
price                23875
Name: 8, dtype: object
symboling                0
normalized-losses      188
make                   bmw
fuel-type              gas
aspiration             std
num-of-doors           two
body-style           sedan
drive-wheels           rwd
engine-location      front
wheel-base           101.2
length               176.8
width                 64.8
height                54.3
curb-weight           2710
engine-type            ohc
num-of-cylinders       six
engine-size            164
fuel-system           mpfi
bore                  3.31
stroke                3.19
compression-ratio      9.0
horsepower             121
peak-rpm              4250
city-mpg                21
highway-mpg             28
price                20970
Name: 12, dtype: object
symboling                0
normalized-losses      188
make                   bmw
fuel-type              gas
aspiration             std
num-of-doors          four
body-style           sedan
drive-wheels           rwd
engine-location      front
wheel-base           101.2
length               176.8
width                 64.8
height                54.3
curb-weight           2765
engine-type            ohc
num-of-cylinders       six
engine-size            164
fuel-system           mpfi
bore                  3.31
stroke                3.19
compression-ratio      9.0
horsepower             121
peak-rpm              4250
city-mpg                21
highway-mpg             28
price                21105
Name: 13, dtype: object
symboling                1
normalized-losses        ?
make                   bmw
fuel-type              gas
aspiration             std
num-of-doors          four
body-style           sedan
drive-wheels           rwd
engine-location      front
wheel-base           103.5
length               189.0
width                 66.9
height                55.7
curb-weight           3055
engine-type            ohc
num-of-cylinders       six
engine-size            164
fuel-system           mpfi
bore                  3.31
stroke                3.19
compression-ratio      9.0
horsepower             121
peak-rpm              4250
city-mpg                20
highway-mpg             25
price                24565
Name: 14, dtype: object
symboling                0
normalized-losses        ?
make                   bmw
fuel-type              gas
aspiration             std
num-of-doors          four
body-style           sedan
drive-wheels           rwd
engine-location      front
wheel-base           103.5
length               189.0
width                 66.9
height                55.7
curb-weight           3230
engine-type            ohc
num-of-cylinders       six
engine-size            209
fuel-system           mpfi
bore                  3.62
stroke                3.39
compression-ratio      8.0
horsepower             182
peak-rpm              5400
city-mpg                16
highway-mpg             22
price                30760
Name: 15, dtype: object
symboling                0
normalized-losses        ?
make                   bmw
fuel-type              gas
aspiration             std
num-of-doors           two
body-style           sedan
drive-wheels           rwd
engine-location      front
wheel-base           103.5
length               193.8
width                 67.9
height                53.7
curb-weight           3380
engine-type            ohc
num-of-cylinders       six
engine-size            209
fuel-system           mpfi
bore                  3.62
stroke                3.39
compression-ratio      8.0
horsepower             182
peak-rpm              5400
city-mpg                16
highway-mpg             22
price                41315
Name: 16, dtype: object
symboling                0
normalized-losses        ?
make                   bmw
fuel-type              gas
aspiration             std
num-of-doors          four
body-style           sedan
drive-wheels           rwd
engine-location      front
wheel-base           110.0
length               197.0
width                 70.9
height                56.3
curb-weight           3505
engine-type            ohc
num-of-cylinders       six
engine-size            209
fuel-system           mpfi
bore                  3.62
stroke                3.39
compression-ratio      8.0
horsepower             182
peak-rpm              5400
city-mpg                15
highway-mpg             20
price                36880
Name: 17, dtype: object
symboling                 0
normalized-losses       145
make                 jaguar
fuel-type               gas
aspiration              std
num-of-doors           four
body-style            sedan
drive-wheels            rwd
engine-location       front
wheel-base            113.0
length                199.6
width                  69.6
height                 52.8
curb-weight            4066
engine-type            dohc
num-of-cylinders        six
engine-size             258
fuel-system            mpfi
bore                   3.63
stroke                 4.17
compression-ratio       8.1
horsepower              176
peak-rpm               4750
city-mpg                 15
highway-mpg              19
price                 32250
Name: 47, dtype: object
symboling                 0
normalized-losses         ?
make                 jaguar
fuel-type               gas
aspiration              std
num-of-doors           four
body-style            sedan
drive-wheels            rwd
engine-location       front
wheel-base            113.0
length                199.6
width                  69.6
height                 52.8
curb-weight            4066
engine-type            dohc
num-of-cylinders        six
engine-size             258
fuel-system            mpfi
bore                   3.63
stroke                 4.17
compression-ratio       8.1
horsepower              176
peak-rpm               4750
city-mpg                 15
highway-mpg              19
price                 35550
Name: 48, dtype: object
symboling                 0
normalized-losses         ?
make                 jaguar
fuel-type               gas
aspiration              std
num-of-doors            two
body-style            sedan
drive-wheels            rwd
engine-location       front
wheel-base            102.0
length                191.7
width                  70.6
height                 47.8
curb-weight            3950
engine-type            ohcv
num-of-cylinders     twelve
engine-size             326
fuel-system            mpfi
bore                   3.54
stroke                 2.76
compression-ratio      11.5
horsepower              262
peak-rpm               5000
city-mpg                 13
highway-mpg              17
price                 36000
Name: 49, dtype: object
symboling                       -1
normalized-losses               93
make                 mercedes-benz
fuel-type                   diesel
aspiration                   turbo
num-of-doors                  four
body-style                   sedan
drive-wheels                   rwd
engine-location              front
wheel-base                   110.0
length                       190.9
width                         70.3
height                        56.5
curb-weight                   3515
engine-type                    ohc
num-of-cylinders              five
engine-size                    183
fuel-system                    idi
bore                          3.58
stroke                        3.64
compression-ratio             21.5
horsepower                     123
peak-rpm                      4350
city-mpg                        22
highway-mpg                     25
price                        25552
Name: 67, dtype: object
symboling                       -1
normalized-losses               93
make                 mercedes-benz
fuel-type                   diesel
aspiration                   turbo
num-of-doors                  four
body-style                   wagon
drive-wheels                   rwd
engine-location              front
wheel-base                   110.0
length                       190.9
width                         70.3
height                        58.7
curb-weight                   3750
engine-type                    ohc
num-of-cylinders              five
engine-size                    183
fuel-system                    idi
bore                          3.58
stroke                        3.64
compression-ratio             21.5
horsepower                     123
peak-rpm                      4350
city-mpg                        22
highway-mpg                     25
price                        28248
Name: 68, dtype: object
symboling                        0
normalized-losses               93
make                 mercedes-benz
fuel-type                   diesel
aspiration                   turbo
num-of-doors                   two
body-style                 hardtop
drive-wheels                   rwd
engine-location              front
wheel-base                   106.7
length                       187.5
width                         70.3
height                        54.9
curb-weight                   3495
engine-type                    ohc
num-of-cylinders              five
engine-size                    183
fuel-system                    idi
bore                          3.58
stroke                        3.64
compression-ratio             21.5
horsepower                     123
peak-rpm                      4350
city-mpg                        22
highway-mpg                     25
price                        28176
Name: 69, dtype: object
symboling                       -1
normalized-losses               93
make                 mercedes-benz
fuel-type                   diesel
aspiration                   turbo
num-of-doors                  four
body-style                   sedan
drive-wheels                   rwd
engine-location              front
wheel-base                   115.6
length                       202.6
width                         71.7
height                        56.3
curb-weight                   3770
engine-type                    ohc
num-of-cylinders              five
engine-size                    183
fuel-system                    idi
bore                          3.58
stroke                        3.64
compression-ratio             21.5
horsepower                     123
peak-rpm                      4350
city-mpg                        22
highway-mpg                     25
price                        31600
Name: 70, dtype: object
symboling                       -1
normalized-losses                ?
make                 mercedes-benz
fuel-type                      gas
aspiration                     std
num-of-doors                  four
body-style                   sedan
drive-wheels                   rwd
engine-location              front
wheel-base                   115.6
length                       202.6
width                         71.7
height                        56.5
curb-weight                   3740
engine-type                   ohcv
num-of-cylinders             eight
engine-size                    234
fuel-system                   mpfi
bore                          3.46
stroke                         3.1
compression-ratio              8.3
horsepower                     155
peak-rpm                      4750
city-mpg                        16
highway-mpg                     18
price                        34184
Name: 71, dtype: object
symboling                        3
normalized-losses              142
make                 mercedes-benz
fuel-type                      gas
aspiration                     std
num-of-doors                   two
body-style             convertible
drive-wheels                   rwd
engine-location              front
wheel-base                    96.6
length                       180.3
width                         70.5
height                        50.8
curb-weight                   3685
engine-type                   ohcv
num-of-cylinders             eight
engine-size                    234
fuel-system                   mpfi
bore                          3.46
stroke                         3.1
compression-ratio              8.3
horsepower                     155
peak-rpm                      4750
city-mpg                        16
highway-mpg                     18
price                        35056
Name: 72, dtype: object
symboling                        0
normalized-losses                ?
make                 mercedes-benz
fuel-type                      gas
aspiration                     std
num-of-doors                  four
body-style                   sedan
drive-wheels                   rwd
engine-location              front
wheel-base                   120.9
length                       208.1
width                         71.7
height                        56.7
curb-weight                   3900
engine-type                   ohcv
num-of-cylinders             eight
engine-size                    308
fuel-system                   mpfi
bore                           3.8
stroke                        3.35
compression-ratio              8.0
horsepower                     184
peak-rpm                      4500
city-mpg                        14
highway-mpg                     16
price                        40960
Name: 73, dtype: object
symboling                        1
normalized-losses                ?
make                 mercedes-benz
fuel-type                      gas
aspiration                     std
num-of-doors                   two
body-style                 hardtop
drive-wheels                   rwd
engine-location              front
wheel-base                   112.0
length                       199.2
width                         72.0
height                        55.4
curb-weight                   3715
engine-type                   ohcv
num-of-cylinders             eight
engine-size                    304
fuel-system                   mpfi
bore                           3.8
stroke                        3.35
compression-ratio              8.0
horsepower                     184
peak-rpm                      4500
city-mpg                        14
highway-mpg                     16
price                        45400
Name: 74, dtype: object
symboling                    3
normalized-losses          186
make                   porsche
fuel-type                  gas
aspiration                 std
num-of-doors               two
body-style           hatchback
drive-wheels               rwd
engine-location          front
wheel-base                94.5
length                   168.9
width                     68.3
height                    50.2
curb-weight               2778
engine-type                ohc
num-of-cylinders          four
engine-size                151
fuel-system               mpfi
bore                      3.94
stroke                    3.11
compression-ratio          9.5
horsepower                 143
peak-rpm                  5500
city-mpg                    19
highway-mpg                 27
price                    22018
Name: 125, dtype: object
symboling                  3
normalized-losses          ?
make                 porsche
fuel-type                gas
aspiration               std
num-of-doors             two
body-style           hardtop
drive-wheels             rwd
engine-location         rear
wheel-base              89.5
length                 168.9
width                   65.0
height                  51.6
curb-weight             2756
engine-type             ohcf
num-of-cylinders         six
engine-size              194
fuel-system             mpfi
bore                    3.74
stroke                   2.9
compression-ratio        9.5
horsepower               207
peak-rpm                5900
city-mpg                  17
highway-mpg               25
price                  32528
Name: 126, dtype: object
symboling                  3
normalized-losses          ?
make                 porsche
fuel-type                gas
aspiration               std
num-of-doors             two
body-style           hardtop
drive-wheels             rwd
engine-location         rear
wheel-base              89.5
length                 168.9
width                   65.0
height                  51.6
curb-weight             2756
engine-type             ohcf
num-of-cylinders         six
engine-size              194
fuel-system             mpfi
bore                    3.74
stroke                   2.9
compression-ratio        9.5
horsepower               207
peak-rpm                5900
city-mpg                  17
highway-mpg               25
price                  34028
Name: 127, dtype: object
symboling                      3
normalized-losses              ?
make                     porsche
fuel-type                    gas
aspiration                   std
num-of-doors                 two
body-style           convertible
drive-wheels                 rwd
engine-location             rear
wheel-base                  89.5
length                     168.9
width                       65.0
height                      51.6
curb-weight                 2800
engine-type                 ohcf
num-of-cylinders             six
engine-size                  194
fuel-system                 mpfi
bore                        3.74
stroke                       2.9
compression-ratio            9.5
horsepower                   207
peak-rpm                    5900
city-mpg                      17
highway-mpg                   25
price                      37028
Name: 128, dtype: object
symboling               -1
normalized-losses       95
make                 volvo
fuel-type              gas
aspiration             std
num-of-doors          four
body-style           sedan
drive-wheels           rwd
engine-location      front
wheel-base           109.1
length               188.8
width                 68.9
height                55.5
curb-weight           3012
engine-type           ohcv
num-of-cylinders       six
engine-size            173
fuel-system           mpfi
bore                  3.58
stroke                2.87
compression-ratio      8.8
horsepower             134
peak-rpm              5500
city-mpg                18
highway-mpg             23
price                21485
Name: 202, dtype: object
symboling                -1
normalized-losses        95
make                  volvo
fuel-type            diesel
aspiration            turbo
num-of-doors           four
body-style            sedan
drive-wheels            rwd
engine-location       front
wheel-base            109.1
length                188.8
width                  68.9
height                 55.5
curb-weight            3217
engine-type             ohc
num-of-cylinders        six
engine-size             145
fuel-system             idi
bore                   3.01
stroke                  3.4
compression-ratio      23.0
horsepower              106
peak-rpm               4800
city-mpg                 26
highway-mpg              27
price                 22470
Name: 203, dtype: object
symboling               -1
normalized-losses       95
make                 volvo
fuel-type              gas
aspiration           turbo
num-of-doors          four
body-style           sedan
drive-wheels           rwd
engine-location      front
wheel-base           109.1
length               188.8
width                 68.9
height                55.5
curb-weight           3062
engine-type            ohc
num-of-cylinders      four

Name: 204, dtype: object

In [7]:
df = df[df['highway-mpg'] > 30]
df

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
18,2,121,chevrolet,gas,std,two,hatchback,fwd,front,88.4,...,61,2bbl,2.91,3.03,9.50,48,5100,47,53,5151
19,1,98,chevrolet,gas,std,two,hatchback,fwd,front,94.5,...,90,2bbl,3.03,3.11,9.60,70,5400,38,43,6295
20,0,81,chevrolet,gas,std,four,sedan,fwd,front,94.5,...,90,2bbl,3.03,3.11,9.60,70,5400,38,43,6575
21,1,118,dodge,gas,std,two,hatchback,fwd,front,93.7,...,90,2bbl,2.97,3.23,9.41,68,5500,37,41,5572
22,1,118,dodge,gas,std,two,hatchback,fwd,front,93.7,...,90,2bbl,2.97,3.23,9.40,68,5500,31,38,6377
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
186,2,94,volkswagen,gas,std,four,sedan,fwd,front,97.3,...,109,mpfi,3.19,3.4,9.00,85,5250,27,34,8495
187,2,94,volkswagen,diesel,turbo,four,sedan,fwd,front,97.3,...,97,idi,3.01,3.4,23.00,68,4500,37,42,9495
188,2,94,volkswagen,gas,std,four,sedan,fwd,front,97.3,...,109,mpfi,3.19,3.4,10.00,100,5500,26,32,9995
192,0,?,volkswagen,diesel,turbo,four,sedan,fwd,front,100.4,...,97,idi,3.01,3.4,23.00,68,4500,33,38,13845
193,0,?,volkswagen,gas,std,four,wagon,fwd,front,100.4,...,109,mpfi,3.19,3.4,9.00,88,5500,25,31,12290

In [8]:
# czyszczenie cen 
df = dataset.copy()

for idx in df.index:
    if dataset.loc[idx, 'price'] == '?':
        dataset.loc[idx, 'price'] = 0

In [9]:
# check pices over 30000
df = dataset.copy()

df = df[df['price'].astype('int') > 30000]
df

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
15,0,?,bmw,gas,std,four,sedan,rwd,front,103.5,...,209,mpfi,3.62,3.39,8.0,182,5400,16,22,30760
16,0,?,bmw,gas,std,two,sedan,rwd,front,103.5,...,209,mpfi,3.62,3.39,8.0,182,5400,16,22,41315
17,0,?,bmw,gas,std,four,sedan,rwd,front,110.0,...,209,mpfi,3.62,3.39,8.0,182,5400,15,20,36880
47,0,145,jaguar,gas,std,four,sedan,rwd,front,113.0,...,258,mpfi,3.63,4.17,8.1,176,4750,15,19,32250
48,0,?,jaguar,gas,std,four,sedan,rwd,front,113.0,...,258,mpfi,3.63,4.17,8.1,176,4750,15,19,35550
49,0,?,jaguar,gas,std,two,sedan,rwd,front,102.0,...,326,mpfi,3.54,2.76,11.5,262,5000,13,17,36000
70,-1,93,mercedes-benz,diesel,turbo,four,sedan,rwd,front,115.6,...,183,idi,3.58,3.64,21.5,123,4350,22,25,31600
71,-1,?,mercedes-benz,gas,std,four,sedan,rwd,front,115.6,...,234,mpfi,3.46,3.1,8.3,155,4750,16,18,34184
72,3,142,mercedes-benz,gas,std,two,convertible,rwd,front,96.6,...,234,mpfi,3.46,3.1,8.3,155,4750,16,18,35056
73,0,?,mercedes-benz,gas,std,four,sedan,rwd,front,120.9,...,308,mpfi,3.8,3.35,8.0,184,4500,14,16,40960
74,1,?,mercedes-benz,gas,std,two,hardtop,rwd,front,112.0,...,304,mpfi,3.8,3.35,8.0,184,4500,14,16,45400
126,3,?,porsche,gas,std,two,hardtop,rwd,rear,89.5,...,194,mpfi,3.74,2.9,9.5,207,5900,17,25,32528
127,3,?,porsche,gas,std,two,hardtop,rwd,rear,89.5,...,194,mpfi,3.74,2.9,9.5,207,5900,17,25,34028
128,3,?,porsche,gas,std,two,convertible,rwd,rear,89.5,...,194,mpfi,3.74,2.9,9.5,207,5900,17,25,37028

In [10]:
# sortowanie = sorting by value
df = dataset.copy()
df['price'] = df['price'].astype('int')
df = df.sort_values('price')
df.head(2)

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
45,0,?,isuzu,gas,std,four,sedan,fwd,front,94.5,...,90,2bbl,3.03,3.11,9.6,70,5400,38,43,0
129,1,?,porsche,gas,std,two,hatchback,rwd,front,98.4,...,203,mpfi,3.94,3.11,10.0,288,5750,17,28,0

In [11]:
# sort by index
df = df.set_index('highway-mpg')
df.sort_index()

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,num-of-cylinders,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,price
highway-mpg,,,,,,,,,,,,,,,,,,,,,
16,1,?,mercedes-benz,gas,std,two,hardtop,rwd,front,112.0,...,eight,304,mpfi,3.8,3.35,8.0,184,4500,14,45400
16,0,?,mercedes-benz,gas,std,four,sedan,rwd,front,120.9,...,eight,308,mpfi,3.8,3.35,8.0,184,4500,14,40960
17,0,?,jaguar,gas,std,two,sedan,rwd,front,102.0,...,twelve,326,mpfi,3.54,2.76,11.5,262,5000,13,36000
18,3,142,mercedes-benz,gas,std,two,convertible,rwd,front,96.6,...,eight,234,mpfi,3.46,3.1,8.3,155,4750,16,35056
18,-1,?,mercedes-benz,gas,std,four,sedan,rwd,front,115.6,...,eight,234,mpfi,3.46,3.1,8.3,155,4750,16,34184
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
47,0,91,toyota,gas,std,four,sedan,fwd,front,95.7,...,four,98,2bbl,3.19,3.03,9.0,70,4800,38,7738
47,0,91,toyota,diesel,std,four,hatchback,fwd,front,95.7,...,four,110,idi,3.27,3.35,22.5,56,4500,38,7788
50,1,128,nissan,diesel,std,two,sedan,fwd,front,94.5,...,four,103,idi,2.99,3.47,21.9,55,4800,45,7099
53,2,121,chevrolet,gas,std,two,hatchback,fwd,front,88.4,...,three,61,2bbl,2.91,3.03,9.5,48,5100,47,5151
54,2,137,honda,gas,std,two,hatchback,fwd,front,86.6,...,four,92,1bbl,2.91,3.41,9.6,58,4800,49,6479

In [12]:
'''
zadnie 1 Wypisz nazwiska uporzadkowane alfabetycznie szecioletnich dziewczynek 
z przedszkola 75  -- nazwa


'''

'\nzadnie 1 Wypisz nazwiska uporzadkowane alfabetycznie szecioletnich dziewczynek \nz przedszkola 75  -- nazwa\n\n\n'

In [13]:
import pandas as pd

# 1 solution
dzieci = pd.read_csv("DZIECI.txt", delimiter=';') 
przedszkola = pd.read_csv("PRZEDSZKOLA.txt", delimiter=';') 
preferencje = pd.read_csv("PREFERENCJE.txt", delimiter=';') 

dzieci.index = dzieci['Pesel']
przedszkola.index = przedszkola['Id_przedszkola']

dzieci = dzieci[(dzieci['Wiek'] == 6) & (dzieci['Plec'] == 'dziewczynka')]
przedszkola = przedszkola[przedszkola['Nazwa_przedszkola'].str.contains("75")]
przedzkole_id = list(przedszkola.index.values)[0]

preferencje = preferencje[preferencje['Id_przedszkola'] == przedzkole_id]
preferencje.index = preferencje['Pesel']
preferencje = preferencje['Id_przedszkola']
preferencje = dict(preferencje)
preferencje = list(preferencje.keys())

def znajdz(row):
    if row['Pesel'] in preferencje:
        return True
    else:
        return False
    

dzieci['preferencje'] = dzieci.apply(znajdz, axis=1)
dzieci = dzieci[dzieci['preferencje'] == True]
dzieci = dzieci.sort_values('Nazwisko')
dzieci

,Pesel,Nazwisko,Imie,Plec,Wiek,preferencje
Pesel,,,,,,
p06240301004,p06240301004,Czeszewska,Paulina,dziewczynka,6,True
p06250600128,p06250600128,Derengowska,Joanna,dziewczynka,6,True
p06272102927,p06272102927,Jasinska,Zuzanna,dziewczynka,6,True
p06261102347,p06261102347,Studzieniecka,Marta,dziewczynka,6,True
p06311001507,p06311001507,Waluszko,Zofia,dziewczynka,6,True

In [14]:
# zlaczenia dataframes po indeksie
# 2nd solution


import pandas as pd
pd.set_option('display.max_columns', None)

# 2 solution
dzieci = pd.read_csv("DZIECI.txt", delimiter=';') 
przedszkola = pd.read_csv("PRZEDSZKOLA.txt", delimiter=';') 
preferencje = pd.read_csv("PREFERENCJE.txt", delimiter=';') 


df_all = preferencje.set_index('Pesel').join(dzieci.set_index('Pesel'))
df_all = df_all.set_index('Id_przedszkola').join(przedszkola.set_index('Id_przedszkola'))
display(df_all.head(2))

df_all[
    (df_all['Nazwa_przedszkola'] == 'Przedszkole nr 75') & 
    (df_all['Wiek'] == 6) & 
    (df_all['Plec'] == 'dziewczynka')].sort_values('Nazwisko')

,Numer_preferencji,Nazwisko,Imie,Plec,Wiek,Nazwa_przedszkola,Liczba_miejsc
Id_przedszkola,,,,,,,
1,1,Pawlowicz,Marlena,dziewczynka,6,Przedszkole nr 1,55
1,1,Toczek,Konrad,chlopiec,6,Przedszkole nr 1,55

,Numer_preferencji,Nazwisko,Imie,Plec,Wiek,Nazwa_przedszkola,Liczba_miejsc
Id_przedszkola,,,,,,,
76,1,Czeszewska,Paulina,dziewczynka,6,Przedszkole nr 75,60
76,1,Derengowska,Joanna,dziewczynka,6,Przedszkole nr 75,60
76,1,Jasinska,Zuzanna,dziewczynka,6,Przedszkole nr 75,60
76,1,Studzieniecka,Marta,dziewczynka,6,Przedszkole nr 75,60
76,1,Waluszko,Zofia,dziewczynka,6,Przedszkole nr 75,60

In [15]:
'''
zadanie 2
- wypisz wszystkie osoby ktore na liscie preferencji maja 3 przedszkola
'''
# solution 1

dzieci = pd.read_csv("DZIECI.txt", delimiter=';') 
przedszkola = pd.read_csv("PRZEDSZKOLA.txt", delimiter=';') 
preferencje = pd.read_csv("PREFERENCJE.txt", delimiter=';') 

df_all = preferencje.set_index('Pesel').join(dzieci.set_index('Pesel')).groupby(["Pesel", "Nazwisko", "Imie"]).size().reset_index(name='count')
df_all = df_all[df_all['count'] == 3]
df_all

             Pesel      Nazwisko      Imie  count
121   p07210503233     Mackowiak   Kryspin      3
132   p07211803936       Stencel   Ksawery      3
142   p07212708544  Gorzelanczyk     Nadia      3
145   p07212900748     Szymanska     Julia      3
164   p07222101065    Dziubanska    Amelia      3
...            ...           ...       ...    ...
2431  p09323004661      Grabania    Oliwia      3
2432  p09323004685           Kot  Antonina      3
2435  p09323004777       Siedlar   Mateusz      3
2440  p09323103834     Konieczny    Szymon      3
2442  p09323107357         Dampc    Szymon      3

[912 rows x 4 columns]

In [16]:
'''
zadanie 3
podaj nazwe przedszkola ktore zostalo wybrane jako pierwszy wybor
podaj nazwy tych osob
'''
dzieci = pd.read_csv("DZIECI.txt", delimiter=';') 
przedszkola = pd.read_csv("PRZEDSZKOLA.txt", delimiter=';') 
preferencje = pd.read_csv("PREFERENCJE.txt", delimiter=';') 

df_all = preferencje.set_index('Pesel').join(dzieci.set_index('Pesel'))
df_all = df_all.set_index('Id_przedszkola').join(przedszkola.set_index('Id_przedszkola'))

df_first = df_all[df_all['Numer_preferencji'] == 1]
df_second = df_all[df_all['Numer_preferencji'] == 2]
df_third = df_all[df_all['Numer_preferencji'] == 3]

merged = list(df_second['Nazwa_przedszkola'].unique()) + list(df_third['Nazwa_przedszkola'].unique())
df_first = df_first[~df_first['Nazwa_przedszkola'].isin(merged)]

print(df_first['Nazwa_przedszkola'].unique()[0])
print(df_first.shape[0])
df_first

Przedszkole nr 61
20

,Numer_preferencji,Nazwisko,Imie,Plec,Wiek,Nazwa_przedszkola,Liczba_miejsc
Id_przedszkola,,,,,,,
45,1,Pydyn,Nikola,dziewczynka,4,Przedszkole nr 61,20
45,1,Tartas,Bartosz,chlopiec,4,Przedszkole nr 61,20
45,1,Sobecka,Zuzanna,dziewczynka,4,Przedszkole nr 61,20
45,1,Werbinski,Maciej,chlopiec,4,Przedszkole nr 61,20
45,1,Kunowska,Anastazja,dziewczynka,4,Przedszkole nr 61,20
45,1,Stolarczyk,Damian,chlopiec,4,Przedszkole nr 61,20
45,1,Litmanowicz,Gracjan,chlopiec,4,Przedszkole nr 61,20
45,1,Schmidtke,Dominika,dziewczynka,3,Przedszkole nr 61,20
45,1,Sumislawski,Maciej,chlopiec,3,Przedszkole nr 61,20
45,1,Mateja,Stanislaw,chlopiec,3,Przedszkole nr 61,20
45,1,Zdolny,Patryk,chlopiec,3,Przedszkole nr 61,20
45,1,Heizig,Nikodem,chlopiec,3,Przedszkole nr 61,20
45,1,Zmuda,Amelia,dziewczynka,3,Przedszkole nr 61,20
45,1,Jasinska,Zuzanna,dziewczynka,3,Przedszkole nr 61,20
45,1,Wegielnik,Igor,chlopiec,3,Przedszkole nr 61,20
45,1,Wisniewska,Dorota,dziewczynka,3,Przedszkole nr 61,20
45,1,Bialaszewski,Mateusz,chlopiec,3,Przedszkole nr 61,20
45,1,Banczyk,Jan,chlopiec,3,Przedszkole nr 61,20
45,1,Frankowska,Amelia,dziewczynka,3,Przedszkole nr 61,20
45,1,Pasierowska,Julia,dziewczynka,3,Przedszkole nr 61,20

In [30]:
'''
Wypisz top 3 przedszkola oblegane 
'''

dzieci = pd.read_csv("DZIECI.txt", delimiter=';') 
przedszkola = pd.read_csv("PRZEDSZKOLA.txt", delimiter=';') 
preferencje = pd.read_csv("PREFERENCJE.txt", delimiter=';') 

# joining przedszkola to preferencje
df_all = preferencje.set_index('Id_przedszkola').join(przedszkola.set_index('Id_przedszkola'))
df_all = df_all.groupby(["Nazwa_przedszkola","Id_przedszkola"]).size().reset_index(name='count').sort_values('count', ascending=False)
df_all.head(3)

    Nazwa_przedszkola  Id_przedszkola  count
41  Przedszkole nr 75              76    406
40  Przedszkole nr 74              56    323
44  Przedszkole nr 84              60    223

In [51]:
'''
Wypisz top 3 przedszkola oblegane 
'''
preferencje = pd.read_csv("PREFERENCJE.txt", delimiter=';') 

df = preferencje.groupby(['Id_przedszkola'])['Pesel'].count()
# df = df.sort_values('Id_przedszkola', ascending=False)
# df.head(3)
df = df.sort_values(ascending=False).head(3)
df = pd.DataFrame(df)
df

                Pesel
Id_przedszkola
76                406
56                323
60                223